export default class Pokemon {
  constructor(
    id: number,
    Row_Value: string,
    Name: string,
    Pokedex_Number: string,
    Img_name: string,
    Generation: string,
    Evolution_Stage: string,
    Evolved: string,
    FamilyID: string,
    Cross_Gen: string,
    Type1: string,
    Type2: string,
    Weather1: string,
    Weather2: string,
    STAT_TOTAL: string,
    ATK: string,
    DEF: string,
    STA: string,
    Legendary: string,
    Aquireable: string,
    Spawns: string,
    Regional: string,
    Raidable: string,
    Hatchable: string,
    Shiny: string,
    Nest: string,
    New: string,
    NotGettable: string,
    Future_Evolve: string,
    CP40: string,
    CP39: string
  ) {}

}
